### ISSUE TITLE
Canceling an audio sets dialogue volume to 0 and doesn't get restored

### ISSUE THREAD

**Issue by catinbetween** [clhammer89/QuestReaderAddon#14]
When canceling an audio from the quest window, it is canceled but afterwards i thought the addon broke until i realized the dialogue volume in the options was set to 0.

I had a quick glance at the code and saw that the function that is canceling the audio sets the dialogue volume to 0 to "cancel" the audio and after waiting for the rest of the audio to finish silently, it was supposed to be active again.
However, for some reason it was not set back to the value it was before or it the original value was not saved correctly. It happened to both me and my boyfriend.
I seems a bit odd to cancel an audio this way, as other similar quest reader addons (like Dialogue UI from Peterodox) don't seem to have this problem.  I wish i could look into it myself but i am too unfamiliar with lua to be of any help with that.

I don't know how other addons handle this problem but if you hadn't already, it could be a good idea to take some inspiration from other addons. 

If all else fails, you could introduce a default dialog volume value that you can set in the settings so you always have a value to restore the value to.

I hope this is helpful.

**Comment by clhammer89** [comment]
Thanks for the feedback! There are a couple of other addons that do something similar to I, however they rotate the sound channels properly so it doesn't seem like anything is being muted. 

I rolled back my stop button until I can properly implement this feature without it breaking audio. I haven't looked into Dialogue UI yet though, so I'm curious if they found a better way!
