### ISSUE TITLE
Mod doesn't work with Dialogue UI addon

### ISSUE THREAD

**Issue by Yupmoh** [clhammer89/QuestReaderAddon#17]
Hey! I love your mod so much, it's actually gotten me quite hooked to the game so thanks for that.

However, there is a very special addon named "Dialogue UI" that's very nice to use as a quest menu. makes it easier to read but sadly this beautiful mod doesn't work with it. I saw you make a comment about it on Curse, is there any progress on this? 

Cheers,
Moh

**Comment by clhammer89** [comment]
Yo! I'm glad to hear you're enjoying the mod. The latest update should have support for dialogue UI, can you give it a try and let me know if you run into issues?

**Comment by Yupmoh** [comment]
Works perfectly fine! Thank you! However, I think an increase in the delay before reading the quest is needed, (I know it's been increased once) it still overlaps with NPC interaction greetings. 
Should I report this in a different issue?

**Comment by Yupmoh** [comment]
Decided to not create a new issue for the delay part, I'm sure you've already gotten it in mind :D, thank you for fixing this
