### ISSUE TITLE
[Suggestion] Add a keybind for playback

### ISSUE THREAD

**Issue by ms411** [clhammer89/QuestReaderAddon#25]
Please add a keybind for audio playback for better compatibility with other quest UI addons

**Comment by Paratus** [comment]
Do you mean to toggle the functionality on and off?

**Comment by ms411** [comment]
To activate the playback, as opposed to autoplay or clicking the button that isn't visible in say for example DialogUI

**Comment by Paratus** [comment]
This has been added to the code and will likely be merged in soon!
